import type { Metadata } from "next";
import "./globals.css";
import BaseLayout from "@/components/BaseLayout";

export const metadata: Metadata = {
    title: "150 minutes a week",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
    return (
        <html lang="en">
            <head>
                <meta charSet="utf-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
            </head>
            <body>
                <BaseLayout>
                    <main>{children}</main>
                </BaseLayout>
            </body>
        </html>
    );
};

export default RootLayout;
